services:
  - type: web
    name: locationapp-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: DATABASE_URL
        value: mysql://u729095573_locationapp:Dsp_76499486@srv2071.hstgr.io:3306/u729095573_locationapp
      - key: CLOUDINARY_CLOUD_NAME
        value: de5zyspyj
      - key: CLOUDINARY_API_KEY
        value: 374527478257815
      - key: CLOUDINARY_API_SECRET
        value: 0wKSmyRf_yGc7NwIXzpfE9mnSe0

